/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lucien.cbaseres;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("main");
    }
}
