/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
tasks.register("name"){
    doLast{
        println("test in auth project")
    }
}

description= "auth description"
version = 23
println(name)
println(version)
println(group)
println(description)
println(buildDir)

println(parent!!.extra["counter"])